export const persons = [
  { name: "Alice", age: 25, city: "New York" },
  { name: "Bob", age: 32, city: "London" },
  { name: "Charlie", age: 47, city: "Paris" },
  { name: "Dave", age: 19, city: "Tokyo" },
  { name: "Eva", age: 41, city: "Sydney" },
  { name: "Frank", age: 28, city: "Toronto" },
  { name: "Grace", age: 36, city: "Los Angeles" },
  { name: "Harry", age: 22, city: "Berlin" },
  { name: "Ivy", age: 29, city: "Melbourne" },
  { name: "Jack", age: 38, city: "San Francisco" },
  { name: "Kate", age: 24, city: "Vancouver" },
  { name: "Liam", age: 31, city: "Boston" },
  { name: "Mia", age: 26, city: "Seattle" },
  { name: "Nick", age: 43, city: "Dubai" },
  { name: "Olivia", age: 35, city: "Miami" },
  { name: "Peter", age: 20, city: "Beijing" },
  { name: "Quinn", age: 27, city: "Houston" },
  { name: "Ryan", age: 34, city: "Chicago" },
  { name: "Samantha", age: 23, city: "Paris" },
  { name: "Tom", age: 39, city: "Barcelona" },
  { name: "Uma", age: 42, city: "Rio de Janeiro" },
  { name: "Victor", age: 30, city: "Shanghai" },
  { name: "Wendy", age: 21, city: "Amsterdam" },
  { name: "Xavier", age: 37, city: "New York" },
  { name: "Yara", age: 44, city: "Dublin" },
  { name: "Zack", age: 33, city: "Moscow" },
  { name: "Amber", age: 25, city: "Los Angeles" },
  { name: "Ben", age: 32, city: "Berlin" },
];
